spring:
  datasource:
    url: jdbc:mysql://user-mgmt-db.crp8vcwiqrfw.us-east-1.rds.amazonaws.com:3306/user_db
    username: admin
    password: testdbpassword
  jpa:
    hibernate:
      ddl-auto: update